### ISSUE TITLE
Click on App logo takes to 404

### ISSUE THREAD

**Issue by scorcism** [intentjs/intent#34]
**Describe the bug**
When click on app header logo, user taken to 404 Page

**To Reproduce**
1. Go to '[tryintent.com](https://tryintent.com/docs/installation)' or relative page from tryintent.com
2. Click on 'Website logo'

**Expected behavior**
User should be taken to home page

**Screenshots**
![image](https://github.com/user-attachments/assets/a6afee32-0298-4a3f-9dda-46c62de63067)

**Comment by MPD12340** [comment]
> **Describe the bug** A clear and concise description of what the bug is. When click on app header logo, user taken to 404 Page
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '[tryintent.com](https://tryintent.com/docs/installation)' or relative page from tryintent.com
> 2. Click on 'Website logo'
> 3. See error
> 
> **Expected behavior** User should be taken to home page
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/69761436/391624202-a6afee32-0298-4a3f-9dda-46c62de63067.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNjM5MDksIm5iZiI6MTczMzE2MzYwOSwicGF0aCI6Ii82OTc2MTQzNi8zOTE2MjQyMDItYTZhZmVlMzItMDI5OC00YTNmLTlkZGEtNDZjNjJkZTYzMDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE4MjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZTAxMDU2NTRlMmI3MDc4NWRkMzE1ZmMzNmE4NTI3ZTk3MmU2NGJmNmU2MzUzMGVlZThjMzFiMzI5MTcyN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7nxMWjXy1uXYJMZeFselqioLSIF-QqEIytZ96pqtkFo)

**Comment by scorcism** [comment]
@MPD12340 you can continue, all the best

**Comment by Jatingupta9120** [comment]
Hi, Is the issue still open? Should I work on it? @scorcism

**Comment by Srayash** [comment]
Clicking the logo currently directs users to a non-existent page `https://tryintent.com/docs`.  The intended destination should be the documentation homepage `https://tryintent.com/docs/installation`.

**Comment by scorcism** [comment]
I think then, the URL on github icon on header should also be changed then :)

**Comment by hafizhpratama** [comment]
It's about the route again @vinayak25 .

**Comment by vinayak25** [comment]
I am trying to figure it out as vitepress doesn't give control of changing the logo url. I think I will have to manually make changes in the html post-build.

**Comment by vinayak25** [comment]
closing this as it has been fixed!
