### ISSUE TITLE
No output when running node intent dev after setup for Windows

### ISSUE THREAD

**Issue by Jatingupta9120** [intentjs/intent#36]
![image](https://github.com/user-attachments/assets/a8ace7b2-0c45-43b0-8197-0cb36db71213)
### Problem:- No output when running node intent dev after setup for Windows

I ran the following steps to set up a new project:

npx new-intent-app@latest
Chose project name new-sample-app, AWS and Redis support.
After setup, I ran:
bash
Copy code
cd new-sample-app
npm i
node intent dev

# Current Output:
![image](https://github.com/user-attachments/assets/1160ef4b-8d63-47fc-8730-3dbae1a5a074)
No output or console response when running node intent dev.

# Expected Output:
on the console it should display port like http://localhost:5001/
It should display:
Visit http://localhost:5001/, and you should be greeted with a message.

Environment:

Node.js version: v21.7.2
npm version: 10.5.0
Windows 11

**Comment by Jatingupta9120** [comment]
@vinayak25 have a look at it

**Comment by vinayak25** [comment]
Thanks @Jatingupta9120 sorry been busy with work, will check it out today

**Comment by vinayak25** [comment]
Marking this issue as closed as this has been fixed in the recent release
