### ISSUE TITLE
please this url  https://tryintent.com/docs/ 

### ISSUE THREAD

**Issue by wasitmirani** [intentjs/intent#42]
not working getting 404 error some time

**Comment by nameerakhter** [comment]
Works fine on my side try disabling extension or switch browsers

**Comment by vikashviraj** [comment]
The URL `https://tryintent.com/docs/` should be replaced with `https://tryintent.com/docs/installation`

Currently, this is occurring —
1. When you click on the Intent icon 
2. At the 404 page, when you click to "Take me home" button
   ![image](https://github.com/user-attachments/assets/817c9051-8b91-4288-8d0d-52fd126380a7)

**Comment by hafizhpratama** [comment]
Same experience the same problem. It just needs improvement in the route.

**Comment by jeet-dhandha-lio** [comment]
@hafizhpratama @vikashviraj 
I have raised a PR for that.
- PR : https://github.com/intentjs/docs/pull/4

**Comment by hafizhpratama** [comment]
case close.

**Comment by vinayak25** [comment]
Closing this issue as it has been fixed. Thanks to @jeet-dhandha-lio @hafizhpratama
